Dex 208 sdk references
skyflowapi/skyflow-android pull request #144
Opened 2023-06-13 05:32 UTC by shivkeshmadasu-skyflow

2023-08-15 23:00 UTC, manny-silva requested changes
More coming tomorrow.

2023-08-17 22:34 UTC, manny-silva requested changes
Nits

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/CollectElementOptions.kt
> +    @Description("Indicates whether the field is marked as required. Defaults to 'false'.")
If \`true\`, the field is required. Defaults to \`false\`.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/CollectElementOptions.kt
> +    @Description("Indicates whether card icon should be enabled (only for CARD_NUMBER inputs).")
If \`true\`, enables the card icon. Defaults to \`true`\.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/Configuration.kt
> +@Description("Contains the parameters required for skyflow client initialisation.")
Parameters to initialize a Skyflow client.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/ContainerType.kt
> +@Description("Contains valid Skyflow container types.")
Skyflow container types.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/ElementType.kt
> +@Description("Contains all the supported skyflow element types.")
Skyflow Element types.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/Init.kt
> +@Description("Initialises skyflow client.")
Initializes the Skyflow client.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/Init.kt
> +    @Description("Configuration for the skyflow client.")
Configuration for the Skyflow client.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/InsertOptions.kt
> +@Description("Contains additional parameters for the insert method.")
Additional parameters for the insert method.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/Options.kt
> +@Description("Contains additional parameters for skyflow client configuration.")
Additional configuration for the Skyflow client.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/Padding.kt
> +@Description("Sets the padding for the collect element which takes all the left, top, right, bottom padding values.")
Padding for Collect Elements. Accepts left, top, right, and bottom padding values.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/RevealContainer.kt
> +@Description("Will contain all Reveal Elements.")
Contains Reveal Elements.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/RevealContainer.kt
> +    @Description("Takes an android context object.")
An Android context element.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/RevealContainer.kt
> +    @Description("Takes a Skyflow.RevealElementInput object.")
A Skyflow.RevealElementInput object.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/RevealContainer.kt
> +    @Description("Takes a Skyflow.RevealElementOptions object.")
A Skyflow.RevealElementOptions object.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/RevealOptions.kt
> +@Description("Additional options for the reveal elements.")
Additional options for Reveal Elements.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/Style.kt
> +@Description("Contains various styles for skyflow elements.")
Style options for elements.

2023-08-17 22:34 UTC, manny-silva commented on Skyflow/src/main/kotlin/Skyflow/Styles.kt
> +@Description("Contains different styles to apply on a skyflow element.")
Styles to apply to elements.

2026-06-16 11:21 UTC, Devesh-Skyflow commented
This PR is being closed as it is no longer relevant. Please re-open or raise a new PR if these changes are still needed.

2026-06-16 11:21 UTC, closed without merging